config/routes.rb
Rails.application.routes.draw do

  resources :event_attendees

  resources :events

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {confirmations: "confirmations"}
  resources :users

  root 'pages#index'
  get 'pages/about'
  get 'pages/process_steps'
  get 'pages/calendar'
  post 'geocoder/search'

  resources :issues
  resources :maps
  resources :council_members
  resources :subscriptions, only: :create
  resources :sms_subscriptions, only: :create

  resources :committees do
    resources :committee_members
  end

end

app/models/council_member.rb
class CouncilMember < ActiveRecord::Base
  extend FriendlyId
  include Notifiable

  has_many :agenda_items
  has_many :committee_members
  has_many :committees, through: :committee_members
  has_many :events_attendees
  has_many :events, through: :event_attendees
  friendly_id :slug_candidates, use: :slugged
  has_many :subscriptions, as: :subscribable

  def full_name
    [first_name, last_name].join(' ')
  end

  def display_name
    "City Council Representative  #{self.full_name} (Ward #{self.ward})"
  end

  def homepage
    "http://www.minneapolismn.gov/ward#{self.ward}/index.htm"
  end

  def image_url
    # guess whose name is misspelt
    "http://www.minneapolismn.gov/www/groups/public/@council/documents/images/#{first_name.downcase.gsub('abdi', 'adbi')}-#{last_name.downcase}.jpg"
  end

  # Try building a slug based on the following fields in
  # increasing order of specificity.
  def slug_candidates
    [
      [:first_name, :last_name],
      [:first_name, :last_name, :ward]
    ]
  end

  def generate_code
    return if self.code.present?
    if self.ward
      self.code||="WARD_#{ward}"
    else
      self.code||=[first_name[0], last_name].join
    end
  end
end

app/controllers/council_members_controller.rb
class CouncilMembersController < ApplicationController
  before_action :set_council_member, only: [:show, :edit, :update, :destroy]

  # GET /council_members
  # GET /council_members.json
  def index
    @council_members = CouncilMember.all
  end

  # GET /council_members/1
  # GET /council_members/1.json
  def show
    @committees = []
    @council_member.committee_members.each do |committee_member|
      @committees << Committee.find(committee_member.committee_id)
    end
  end

  # GET /council_members/new
  def new
    @council_member = CouncilMember.new
  end

  # GET /council_members/1/edit
  def edit
  end

  # POST /council_members
  # POST /council_members.json
  def create
    @council_member = CouncilMember.new(council_member_params)

    respond_to do |format|
      if @council_member.save
        format.html { redirect_to @council_member, notice: 'Council member was successfully created.' }
        format.json { render :show, status: :created, location: @council_member }
      else
        format.html { render :new }
        format.json { render json: @council_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /council_members/1
  # PATCH/PUT /council_members/1.json
  def update
    respond_to do |format|
      if @council_member.update(council_member_params)
        format.html { redirect_to @council_member, notice: 'Council member was successfully updated.' }
        format.json { render :show, status: :ok, location: @council_member }
      else
        format.html { render :edit }
        format.json { render json: @council_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /council_members/1
  # DELETE /council_members/1.json
  def destroy
    @council_member.destroy
    respond_to do |format|
      format.html { redirect_to council_members_url, notice: 'Council member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_council_member
    @council_member = CouncilMember.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def council_member_params
    params.require(:council_member).permit(:ward, :first_name, :last_name, :committee_member_id, :code)
  end
end

app/helpers/council_members_helper.rb
module CouncilMembersHelper
end

app/views/council_members/_form.html.erb
<%= form_for(@council_member) do |f| %>
  <% if @council_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@council_member.errors.count, "error") %> prohibited this council_member from being saved:</h2>

      <ul>
      <% @council_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ward %><br>
    <%= f.text_field :ward %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
    <div class="field">
      <%= f.label :code %><br>
      <%= f.text_field :code %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/council_members/edit.html.erb
<h1>Editing council_member</h1>

<%= render 'form' %>

<%= link_to 'Show', @council_member %> |
<%= link_to 'Back', council_members_path %>

app/views/council_members/index.html.erb
<h1>Listing council_members</h1>

<table>
  <thead>
    <tr>
      <th>Ward</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Committees</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @council_members.each do |council_member| %>
      <tr>
        <td><%= council_member.ward %></td>
        <td><%= council_member.first_name %></td>
        <td><%= council_member.last_name %></td>
        <td><% council_member.committee_members.each do |committee_member| %>
          <%= Committee.find(committee_member.committee.id).name %> 
          <% end %></td>
        <td><%= link_to 'Show', council_member %></td>
        <td><%= link_to 'Edit', edit_council_member_path(council_member) %></td>
        <td><%= link_to 'Destroy', council_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Council member', new_council_member_path %>

app/views/council_members/new.html.erb
<h1>New council_member</h1>

<%= render 'form' %>

<%= link_to 'Back', council_members_path %>

app/views/council_members/show.html.erb
  <h1 class="page-header">
    <%= @council_member.first_name + " " + @council_member.last_name %>
    <br />
    <small>Ward <%= @council_member.ward %> City Council Representative</small>
  </h1>

  <%= render partial: "shared/subscription_form", locals: {subscribable: @council_member} %>

  <div class="row">
    <div class="col-md-6">
      <p>
        <strong>Phone:</strong>
        <%= @council_member.phone %>
      </p>
      <p>
        <strong>Email:</strong>
        <%= @council_member.email %>
      </p>
      <p>
        <strong>Neighborhoods:</strong>
        <%= @council_member.neighborhoods %>
      </p>
    </div>
    <div class="col-md-6">
      <img src="<%= @council_member.image_url %>">
    </div>
  </div>

  <hr>
  <!-- begin row -->
  <h4>Committee Participation and Activities</h4>
  <div class="row">
    <div class="col-md-11">
      <div class="panel-group" id="accordion">
        <% @committees.each do |committee| %>
        <div class="panel panel-inverse">
          <div class="panel-heading">
            <h3 class="panel-title">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= committee.id %>">
                <i class="fa fa-plus-circle pull-right"></i> 
                <%= committee.name %>
              </a>
            </h3>
          </div>
          <div id="collapse<%= committee.id %>" class="panel-collapse collapse ">
            <div class="panel-body">
              <h5>Recent Meetings</h5>
              <% committee.events.each do |event| %>
              <%= event.date %>: <%= event.event_type %>
              <ul>
                <% event.agenda_items.take(3).each do |agenda_items| %>
                  <li>agenda_item.properties["description"]</li>
                <% end %>
                <%= link_to "Read More", event_path(event.id) %>
              </ul>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>  
  </div>

  <%= render partial: "shared/timeline", locals: {agenda_items: @council_member.agenda_items.timeline} %>

  <%= link_to 'Edit', edit_council_member_path(@council_member) %> |
  <%= link_to 'Back', council_members_path %>
</div>