config/routes.rb
Rails.application.routes.draw do

  resources :event_attendees

  resources :events

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {confirmations: "confirmations"}
  resources :users

  root 'pages#index'
  get 'pages/about'
  get 'pages/process_steps'
  get 'pages/calendar'
  post 'geocoder/search'

  resources :issues
  resources :maps
  resources :council_members
  resources :subscriptions, only: :create
  resources :sms_subscriptions, only: :create

  resources :committees do
    resources :committee_members
  end

end

app/models/event_attendee.rb
class EventAttendee < ActiveRecord::Base
  belongs_to :council_member
  belongs_to :event
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  before_action :set_event_attendee, only: [:show, :edit, :update, :destroy]

  # GET /event_attendees
  def index
    @event_attendees = EventAttendee.all
  end

  # GET /event_attendees/1
  def show
  end

  # GET /event_attendees/new
  def new
    @event_attendee = EventAttendee.new
  end

  # GET /event_attendees/1/edit
  def edit
  end

  # POST /event_attendees
  def create
    @event_attendee = EventAttendee.new(event_attendee_params)

    if @event_attendee.save
      redirect_to @event_attendee, notice: 'Event attendee was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /event_attendees/1
  def update
    if @event_attendee.update(event_attendee_params)
      redirect_to @event_attendee, notice: 'Event attendee was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /event_attendees/1
  def destroy
    @event_attendee.destroy
    redirect_to event_attendees_url, notice: 'Event attendee was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_attendee
      @event_attendee = EventAttendee.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_attendee_params
      params.require(:event_attendee).permit(:voting_setting, :meeting_status, :order_of_appearance, :council_member_id, :event_id)
    end
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/views/event_attendees/_form.html.erb
<%= form_for(@event_attendee) do |f| %>
  <% if @event_attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_attendee.errors.count, "error") %> prohibited this event_attendee from being saved:</h2>

      <ul>
      <% @event_attendee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :voting_setting %><br>
    <%= f.text_field :voting_setting %>
  </div>
  <div class="field">
    <%= f.label :meeting_status %><br>
    <%= f.text_field :meeting_status %>
  </div>
  <div class="field">
    <%= f.label :order_of_appearance %><br>
    <%= f.text_field :order_of_appearance %>
  </div>
  <div class="field">
    <%= f.label :council_member_id %><br>
    <%= f.text_field :council_member_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.text_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_attendees/edit.html.erb
<h1>Editing event_attendee</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_attendee %> |
<%= link_to 'Back', event_attendees_path %>

app/views/event_attendees/index.html.erb
<h1>Listing event_attendees</h1>

<table>
  <thead>
    <tr>
      <th>Voting setting</th>
      <th>Meeting status</th>
      <th>Order of appearance</th>
      <th>Council member</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_attendees.each do |event_attendee| %>
      <tr>
        <td><%= event_attendee.voting_setting %></td>
        <td><%= event_attendee.meeting_status %></td>
        <td><%= event_attendee.order_of_appearance %></td>
        <td><%= event_attendee.council_member %></td>
        <td><%= event_attendee.event %></td>
        <td><%= link_to 'Show', event_attendee %></td>
        <td><%= link_to 'Edit', edit_event_attendee_path(event_attendee) %></td>
        <td><%= link_to 'Destroy', event_attendee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event attendee', new_event_attendee_path %>

app/views/event_attendees/new.html.erb
<h1>New event_attendee</h1>

<%= render 'form' %>

<%= link_to 'Back', event_attendees_path %>

app/views/event_attendees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Voting setting:</strong>
  <%= @event_attendee.voting_setting %>
</p>

<p>
  <strong>Meeting status:</strong>
  <%= @event_attendee.meeting_status %>
</p>

<p>
  <strong>Order of appearance:</strong>
  <%= @event_attendee.order_of_appearance %>
</p>

<p>
  <strong>Council member:</strong>
  <%= @event_attendee.council_member %>
</p>

<p>
  <strong>Event:</strong>
  <%= @event_attendee.event %>
</p>

<%= link_to 'Edit', edit_event_attendee_path(@event_attendee) %> |
<%= link_to 'Back', event_attendees_path %>