config/routes.rb
Rails.application.routes.draw do

  resources :event_attendees

  resources :events

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {confirmations: "confirmations"}
  resources :users

  root 'pages#index'
  get 'pages/about'
  get 'pages/process_steps'
  get 'pages/calendar'
  post 'geocoder/search'

  resources :issues
  resources :maps
  resources :council_members
  resources :subscriptions, only: :create
  resources :sms_subscriptions, only: :create

  resources :committees do
    resources :committee_members
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :committee
  has_many :event_attendees
  has_many :council_members, through: :event_attendees
  has_many :agenda_items

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(:description, :date, :agenda_url, :archive_status, :committee_id, :event_type)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :agenda_url %><br>
    <%= f.text_field :agenda_url %>
  </div>
  <div class="field">
    <%= f.label :archive_status %><br>
    <%= f.text_field :archive_status %>
  </div>
  <div class="field">
    <%= f.label :committee_id %><br>
    <%= f.text_field :committee_id %>
  </div>
  <div class="field">
    <%= f.label :event_type %><br>
    <%= f.text_field :event_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index-draft.html.erb
<h1>Meetings and Events</h1>

<!-- begin page-header -->
<h1 class="page-header">Calendar <small>header small text goes here...</small></h1>
<!-- end page-header -->
<!-- begin panel -->
<div class="panel panel-inverse">
  <div class="panel-heading">
    <div class="panel-heading-btn">
        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
    </div>
    <h4 class="panel-title">Calendar</h4>
  </div>
  <div class="panel-body p-0">
    <div class="vertical-box">
      <div class="vertical-column p-15 bg-silver width-sm">
        <div id="external-events" class="calendar-event width-sm">
          <h4 class=" m-b-20">Draggable Events</h4>
          <div class="external-event bg-purple" data-bg="bg-purple" data-title="Discussion" data-media="<i class='fa fa-comments'></i>" data-desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit.">
              <h5><i class="fa fa-comments fa-lg fa-fw"></i> Discussion</h5>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
          </div>
          <div class="external-event bg-blue" data-bg="bg-blue" data-title="Dinner" data-media="<i class='fa fa-cutlery'></i>" data-desc="Cum sociis natoque penatibus et magnis dis parturient montes."> 
              <h5><i class="fa fa-cutlery fa-lg fa-fw"></i> Dinner</h5>
              <p>Cum sociis natoque penatibus et magnis dis parturient montes.</p>
          </div>
          <div class="external-event bg-green" data-bg="bg-green" data-title="Brainstorming" data-media="<i class='fa fa-lightbulb-o'></i>" data-desc="Mauris tristique massa eu venenatis semper. Phasellus a nibh nisi.">
              <h5><i class="fa fa-lightbulb-o fa-lg fa-fw"></i> Brainstorming</h5>
              <p>Mauris tristique massa eu venenatis semper. Phasellus a nibh nisi.</p>
          </div>
          <div class="external-event bg-orange" data-bg="bg-orange" data-title="Performance Rating" data-media="<i class='fa fa-tasks'></i>" data-desc="Class aptent taciti sociosqu ad litora torquent per conubia nostra.">
               <h5><i class="fa fa-tasks fa-lg fa-fw"></i> Performance Rating</h5>
              <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra.</p>
          </div>
          <div class="external-event bg-red" data-bg="bg-red" data-title="Video Shooting" data-media="<i class='fa fa-video-camera'></i>" data-desc="Donec ligula nisi, tempus eu egestas id, auctor sit amet velit.">
              <h5><i class="fa fa-video-camera fa-lg fa-fw"></i> Video Shooting</h5>
              <p>Donec ligula nisi, tempus eu egestas id, auctor sit amet velit.</p>
          </div>
          <div class="checkbox">
              <input type="checkbox" id="drop-remove" />
              <label for="drop-remove">remove after drop</label>
          </div>
        </div>
      </div>
      <div id="calendar" class="vertical-column p-15 calendar"></div>
    </div>
  </div>
</div>
<!-- end panel -->
<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Date</th>
      <th>Agenda url</th>
      <th>Archive status</th>
      <th>Committee</th>
      <th>Event type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.description %></td>
        <td><%= event.date %></td>
        <td><%= event.agenda_url %></td>
        <td><%= event.archive_status %></td>
        <td><%= event.committee %></td>
        <td><%= event.event_type %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>


</div>
<!-- end #content -->

<script>
$(document).ready(function() {
  Calendar.init();
  });
</script>

app/views/events/index.html.erb
<!-- begin page-header -->
<h1 class="page-header">Calendar <small>Coming Soon</small></h1>
<!-- end page-header -->
<!-- begin panel -->
<div class="panel panel-inverse">
  <div class="panel-heading">
    <div class="panel-heading-btn">
        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
        <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
    </div>
    <h4 class="panel-title">Calendar</h4>
  </div>
  <div class="panel-body p-0">
    <div class="vertical-box">
      <div class="vertical-column p-15 bg-silver width-sm">
        <div id="external-events" class="calendar-event width-sm">
          <h4 class=" m-b-20">Events</h4>
          <div class="external-event bg-purple" data-bg="bg-purple" data-title="" data-media="<i class='fa fa-comments'></i>" data-desc="">
              
          </div>
          <div class="external-event bg-blue" data-bg="bg-blue" data-title="" data-media="<i class='fa fa-cutlery'></i>" data-desc=""> 
              
          </div>
          <div class="external-event bg-green" data-bg="bg-green" data-title="" data-media="<i class='fa fa-lightbulb-o'></i>" data-desc="">
              
          </div>
          <div class="external-event bg-orange" data-bg="bg-orange" data-title="" data-media="<i class='fa fa-tasks'></i>" data-desc="">
          </div>
          <div class="external-event bg-red" data-bg="bg-red" data-title="" data-media="<i class='fa fa-video-camera'></i>" data-desc="">
          </div>
          <div class="checkbox">
              <input type="checkbox" id="drop-remove" />
              <label for="drop-remove">remove after drop</label>
          </div>
        </div>
      </div>
      <div id="calendar" class="vertical-column p-15 calendar"></div>
    </div>
  </div>
</div>
<!-- end panel -->
</div>
<!-- end #content -->

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Agenda url:</strong>
  <%= @event.agenda_url %>
</p>

<p>
  <strong>Archive status:</strong>
  <%= @event.archive_status %>
</p>

<p>
  <strong>Committee:</strong>
  <%= @event.committee %>
</p>

<p>
  <strong>Event type:</strong>
  <%= @event.event_type %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>