config/routes.rb
Rails.application.routes.draw do

  resources :event_attendees

  resources :events

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {confirmations: "confirmations"}
  resources :users

  root 'pages#index'
  get 'pages/about'
  get 'pages/process_steps'
  get 'pages/calendar'
  post 'geocoder/search'

  resources :issues
  resources :maps
  resources :council_members
  resources :subscriptions, only: :create
  resources :sms_subscriptions, only: :create

  resources :committees do
    resources :committee_members
  end

end

app/models/committee.rb
class Committee < ActiveRecord::Base
  extend FriendlyId
  include Notifiable

  has_many :events
  has_many :agenda_items
  has_many :committee_members
  has_many :council_members, through: :committee_members
  has_many :subscriptions, as: :subscribable

  friendly_id :name, use: :slugged

  def display_name
    "City Council Committee: #{self.name}"
  end

end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  before_action :set_committee, only: [:show, :edit, :update, :destroy]

  # GET /committees
  # GET /committees.json
  def index
    @committees = Committee.all
  end

  # GET /committees/1
  # GET /committees/1.json
  def show
  end

  # GET /committees/new
  def new
    @committee = Committee.new
  end

  # GET /committees/1/edit
  def edit
  end

  # POST /committees
  # POST /committees.json
  def create
    @committee = Committee.new(committee_params)

    respond_to do |format|
      if @committee.save
        format.html { redirect_to @committee, notice: 'Committee was successfully created.' }
        format.json { render :show, status: :created, location: @committee }
      else
        format.html { render :new }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /committees/1
  # PATCH/PUT /committees/1.json
  def update
    respond_to do |format|
      if @committee.update(committee_params)
        format.html { redirect_to @committee, notice: 'Committee was successfully updated.' }
        format.json { render :show, status: :ok, location: @committee }
      else
        format.html { render :edit }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /committees/1
  # DELETE /committees/1.json
  def destroy
    @committee.destroy
    respond_to do |format|
      format.html { redirect_to committees_url, notice: 'Committee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_committee
      @committee = Committee.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def committee_params
      params.require(:committee).permit(:name, :type, :info_url, :code)
    end
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/views/committees/_form.html.erb
<%= form_for(@committee) do |f| %>
  <% if @committee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@committee.errors.count, "error") %> prohibited this committee from being saved:</h2>

      <ul>
      <% @committee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :comm_type %><br>
    <%= f.text_field :comm_type %>
  </div>
  <div class="field">
    <%= f.label :info_url %><br>
    <%= f.text_field :info_url %>
  </div>
    <div class="field">
      <%= f.label :code %><br>
      <%= f.text_field :code %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/committees/edit.html.erb
<h1>Editing committee</h1>

<%= render 'form' %>

<%= link_to 'Show', @committee %> |
<%= link_to 'Back', committees_path %>

app/views/committees/index.html.erb
<h1>Listing committees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Info url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @committees.each do |committee| %>
      <tr>
        <td><%= committee.name %></td>
        <td><%= committee.comm_type %></td>
        <td><%= committee.info_url %></td>
        <td><%= link_to 'Show', committee %></td>
        <td><%= link_to 'Edit', edit_committee_path(committee) %></td>
        <td><%= link_to 'Destroy', committee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Committee', new_committee_path %>

app/views/committees/new.html.erb
<h1>New committee</h1>

<%= render 'form' %>

<%= link_to 'Back', committees_path %>

app/views/committees/show.html.erb
<h1 class="page-header">
  <%= @committee.name %> Committee
  <br />
  <small></small>
</h1>
<%= render partial: "shared/subscription_form", locals: {subscribable: @committee} %>
<div class="row">
  <div class="col-md-6">
		<p>
		  <strong>Type:</strong>
		  <%= @committee.comm_type %>
		</p>
		<p>
		  <strong>Members:</strong>
		  <ul>
			  <% @committee.committee_members.each do |committee_member| %>
			  	<li><%= link_to CouncilMember.find(committee_member.council_member_id).full_name, council_member_path(committee_member.council_member_id) %></li>
			  <% end %>
			</ul>
		</p>
		<p>
		  <strong>More Info:</strong>
		  <%= link_to "Minneapolis City Council Committee Info Page", @committee.info_url %>
		</p>
	</div>
	<div class="col-md-6">
		<p>
		  <strong>Recent Meetings:</strong>
		  <ul>
			  <% @committee.events.each do |event| %>
			  	<li><%= event.date %>: <%= link_to event.event_type, event_path(event.id) %></li>
			  <% end %>
			</ul>
		</p>
	</div>
</div>
<hr>

<%= link_to 'Edit', edit_committee_path(@committee) %> |
<%= link_to 'Back', committees_path %>